/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")
    }

    maven {
        url = uri("https://repo.extendedclip.com/content/repositories/placeholderapi/")
    }

    maven {
        url = uri("https://jitpack.io")
    }

    maven {
        url = uri("https://jcenter.bintray.com")
    }

    maven {
        url = uri("https://s01.oss.sonatype.org/content/repositories/snapshots/")
    }

    maven {
        url = uri("https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/")
    }

    maven {
        url = uri("https://oss.sonatype.org/content/repositories/snapshots/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    compileOnly("org.spigotmc:spigot-api:1.16.1-R0.1-SNAPSHOT")
    compileOnly("me.clip:placeholderapi:2.10.9")
    compileOnly("com.github.the-h-team:Enterprise:1.5")
    compileOnly("com.github.webbukkit:dynmap-api:v2.5")
    compileOnly("org.jetbrains:annotations:23.0.0")
    compileOnly("com.github.the-h-team.Panther:panther-placeholders:1.0.0")
    compileOnly("com.github.the-h-team.Panther:panther-common:1.0.0")
    compileOnly("com.github.the-h-team.Labyrinth:labyrinth-gui:1.8.2")
    compileOnly("com.github.the-h-team.Labyrinth:labyrinth-regions:1.8.2")
    compileOnly("com.github.the-h-team.Panther:panther-paste:1.0.0")
    compileOnly("com.github.the-h-team.Labyrinth:labyrinth-common:1.8.2")
    compileOnly("com.github.the-h-team.Labyrinth:labyrinth-skulls:1.8.2")
}

group = "com.github.sanctum"
version = "1.4.3"
description = "ClansPro"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
