/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "tether"
sequenceOf(
    "api",
    "cli"
).forEach {
    include("tether-$it")
    project(":tether-$it").projectDir = file(it)
}
